import PDFDocument from 'pdfkit';
import { parseInvoice } from '../invoice-xml.js';
import { mockInvoiceInput } from './invoice-input.js';
import type { MockInvoiceInput } from './invoice-input.js';

function escapeXml(value: string): string {
    return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

export function sampleXml(sequence: number, cif: string, issued: string, input?: MockInvoiceInput): string {
    const suppliers = ['Demo Office Supplies SRL', 'Demo Internet Services SRL', 'Demo Consulting SRL'];
    const custom = input ? mockInvoiceInput(input) : undefined;
    const supplier = escapeXml(custom?.supplierName ?? suppliers[(sequence - 1) % suppliers.length]);
    // Custom amounts mean invoice amount. No tax rate is inferred from the two-field form.
    const net = custom?.amountRon ?? '120.00';
    const tax = custom ? '0.00' : '25.20';
    const total = custom?.amountRon ?? '145.20';
    return `<?xml version="1.0" encoding="UTF-8"?>
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
    xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
    xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2">
    <cbc:ID>DEMO-${String(sequence).padStart(4, '0')}</cbc:ID>
    <cbc:IssueDate>${issued}</cbc:IssueDate><cbc:DueDate>${issued}</cbc:DueDate>
    <cbc:InvoiceTypeCode>380</cbc:InvoiceTypeCode><cbc:DocumentCurrencyCode>RON</cbc:DocumentCurrencyCode>
    <cbc:Note>SYNTHETIC DEVELOPMENT INVOICE. NOT A FISCAL DOCUMENT.</cbc:Note>
    <cac:AccountingSupplierParty><cac:Party>
        <cac:PartyTaxScheme><cbc:CompanyID>RO99999990</cbc:CompanyID></cac:PartyTaxScheme>
        <cac:PartyLegalEntity><cbc:RegistrationName>${supplier}</cbc:RegistrationName></cac:PartyLegalEntity>
    </cac:Party></cac:AccountingSupplierParty>
    <cac:AccountingCustomerParty><cac:Party><cac:PartyLegalEntity>
        <cbc:RegistrationName>Demo Customer</cbc:RegistrationName><cbc:CompanyID>${cif}</cbc:CompanyID>
    </cac:PartyLegalEntity></cac:Party></cac:AccountingCustomerParty>
    <cac:TaxTotal><cbc:TaxAmount currencyID="RON">${tax}</cbc:TaxAmount></cac:TaxTotal>
    <cac:LegalMonetaryTotal>
        <cbc:TaxExclusiveAmount currencyID="RON">${net}</cbc:TaxExclusiveAmount>
        <cbc:TaxInclusiveAmount currencyID="RON">${total}</cbc:TaxInclusiveAmount>
        <cbc:PayableAmount currencyID="RON">${total}</cbc:PayableAmount>
    </cac:LegalMonetaryTotal>
    <cac:InvoiceLine><cbc:ID>1</cbc:ID><cbc:InvoicedQuantity unitCode="C62">1</cbc:InvoicedQuantity>
        <cbc:LineExtensionAmount currencyID="RON">${net}</cbc:LineExtensionAmount>
        <cac:Item><cbc:Name>Simulated goods or services</cbc:Name></cac:Item>
        <cac:Price><cbc:PriceAmount currencyID="RON">${net}</cbc:PriceAmount></cac:Price>
    </cac:InvoiceLine>
</Invoice>`;
}

export async function samplePdf(xml: Uint8Array): Promise<Buffer> {
    const invoice = parseInvoice(xml);
    return new Promise((resolve, reject) => {
        const document = new PDFDocument({ size: 'A4', margin: 50 });
        const chunks: Buffer[] = [];
        document.on('data', chunk => chunks.push(chunk));
        document.on('error', reject);
        document.on('end', () => resolve(Buffer.concat(chunks)));
        document.fillColor('#b45309').fontSize(12).text('SIMULATED ANAF DATA — NOT A FISCAL DOCUMENT');
        document.moveDown(2).fillColor('#0f172a').fontSize(26).text(`Invoice ${invoice.number}`);
        document.moveDown().fontSize(12).text(invoice.supplier).text(`Issued: ${invoice.issueDate}`);
        document.moveDown(2);
        for (const line of invoice.lines) document.text(`${line.description}    ${line.quantity}    ${line.amount} ${invoice.currency}`);
        document.moveDown(2).text(`Net: ${invoice.net} ${invoice.currency}`).text(`Tax: ${invoice.tax} ${invoice.currency}`);
        document.fontSize(18).text(`Total: ${invoice.total} ${invoice.currency}`);
        document.moveDown(2).fontSize(10).fillColor('#64748b').text('Generated by the local simulator. This is not ANAF\'s PDF layout.');
        document.end();
    });
}
