import { test, expect } from '@playwright/test';

test('administrator can browse invoices, inspect details, change polling and use mobile layout', async ({ page }, info) => {
    const errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto('/');
    await page.getByLabel('Email', { exact: true }).fill('admin@example.test');
    await page.getByLabel('Password', { exact: true }).fill('local-development-only');
    await page.getByRole('button', { name: /Sign in/ }).click();
    await expect(page.getByRole('heading', { name: 'Your invoice inbox' })).toBeVisible();
    await expect(page.locator('.invoice-link').first()).toBeVisible();
    await page.locator('.invoice-link').first().click();
    await expect(page.locator('.details')).toBeVisible();
    await expect(page.locator('.details .totals')).toContainText(/Invoice amount \d+\.\d{2} RON/);
    await page.getByRole('button', { name: /Close/ }).click();
    await page.screenshot({ path: info.outputPath('desktop.png'), fullPage: true });
    await page.getByRole('button', { name: /Settings/ }).click();
    const interval = page.getByLabel('Polling interval (seconds)');
    const previous = await interval.inputValue();
    await interval.fill('45');
    await page.getByRole('button', { name: 'Save entity settings' }).click();
    await expect(page.getByRole('status')).toContainText('Entity settings saved');
    await interval.fill(previous);
    await page.getByRole('button', { name: 'Save entity settings' }).click();
    await page.getByRole('button', { name: /Invoice inbox/ }).click();
    await page.getByLabel('Search invoices').fill('no-such-supplier');
    await expect(page.getByRole('heading', { name: 'No matching invoices' })).toBeVisible();
    await page.getByLabel('Search invoices').fill('');
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.getByRole('heading', { name: 'Your invoice inbox' })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
    await page.screenshot({ path: info.outputPath('mobile.png'), fullPage: true });
    expect(errors).toEqual([]);
});

test('simulated invoice form supports cancellation, validation and custom invoice creation', async ({ page }, info) => {
    await page.goto('/');
    await page.getByLabel('Email', { exact: true }).fill('admin@example.test');
    await page.getByLabel('Password', { exact: true }).fill('local-development-only');
    await page.getByRole('button', { name: /Sign in/ }).click();
    await page.getByRole('button', { name: /Mocked ANAF/ }).click();
    const create = page.getByRole('button', { name: /Create simulated invoice/ });
    const dialog = page.getByRole('dialog', { name: 'Create simulated invoice' });
    let invoiceRequests = 0;
    page.on('request', request => {
        if (new URL(request.url()).pathname === '/api/mock' && request.method() === 'POST' && request.postDataJSON()?.action === 'invoice') invoiceRequests++;
    });
    await create.click();
    await expect(dialog).toBeVisible();
    await expect(dialog.getByLabel('Supplier name')).toBeFocused();
    await dialog.getByRole('button', { name: 'Cancel' }).click();
    await expect(dialog).not.toBeVisible();
    await expect(create).toBeFocused();
    expect(invoiceRequests).toBe(0);
    await create.click();
    await page.keyboard.press('Escape');
    await expect(dialog).not.toBeVisible();
    await create.click();
    const supplier = `Browser & Supplies ${Date.now()}`;
    await dialog.getByLabel('Supplier name').fill(supplier);
    await dialog.getByLabel('Amount (RON)').fill('0');
    await dialog.getByRole('button', { name: 'Create invoice', exact: true }).click();
    await expect(dialog.getByRole('alert')).toContainText('greater than zero');
    expect(invoiceRequests).toBe(0);
    await dialog.getByLabel('Amount (RON)').fill('1234,56');
    await expect(dialog.getByRole('alert')).not.toBeVisible();
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(dialog).toBeInViewport();
    await page.screenshot({ path: info.outputPath('invoice-form.png'), fullPage: true });
    await dialog.getByRole('button', { name: 'Create invoice', exact: true }).click();
    await expect(dialog).not.toBeVisible();
    await expect(page.getByRole('status')).toContainText(/Simulated invoice DEMO-\d+ created/);
    expect(invoiceRequests).toBe(1);
    await page.getByRole('button', { name: /Sync now/ }).click();
    await page.getByRole('button', { name: /Invoice inbox/ }).click();
    const row = page.getByRole('row').filter({ hasText: supplier });
    await expect(row).toBeVisible({ timeout: 30000 });
    await expect(row).toContainText('1234.56 RON');
    await row.getByRole('button').click();
    await expect(page.locator('.details')).toContainText(supplier);
    await expect(page.locator('.details .totals')).toContainText('Invoice amount 1234.56 RON');
    await expect(row.getByRole('link', { name: 'PDF ↓' })).toBeVisible({ timeout: 30000 });
});
